[project]
name = "investopedia-leaderboard"
version = "0.1.0"
description = "The official leaderboard for the Leland High School Investopedia Game"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
make_portfolio_links = "python ./backend/src/get_portfolios_from_leaderboard.py"
main = "python ./backend/src/main.py"
make_webpage = "rm index.html && python ./backend/src/make_webpage.py >> index.html"
git_push = "git add -A . &&	git commit -m 'leaderboard update' && git push origin"
all = {depends-on = ["main", "git_push"]}

[dependencies]
requests = ">=2.32.3,<2.33"
beautifulsoup4 = ">=4.12.3,<4.13"
selenium = ">=4.25.0,<4.26"
pandas = ">=2.2.3,<2.3"
flask = ">=3.0.3,<3.1"
ruff = ">=0.7.1,<0.8"
scipy = ">=1.14.1,<2"
babel = ">=2.14.0,<3"
pre-commit = ">=4.0.1,<5"
numpy = "1.*"
python = ">=3.12.7,<3.13"
polars = ">=1.15.0,<2"

[pypi-dependencies]
yfinance = { version = ">=0.2.48, <0.3", extras = ["nospam", "repair"] }
python-dotenv = ">=1.0.1, <2"
playwright = ">=1.48.0, <2"
podcastfy = ">=0.4.1, <0.5"
fpdf2 = ">=2.8.1, <3"
